version: '3.8'
services:
  envoy:
    image: envoyproxy/envoy:v1.18.3
    container_name: proxy
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "9999:9999" 
      - "9901:9901"
    command: /usr/local/bin/envoy -c /etc/envoy/envoy.yaml
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "100M"
    depends_on:
      - api-01
      - api-02

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50M"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: rinhadebackend
      POSTGRES_USER: fidelissauro
      POSTGRES_PASSWORD: doutorequemtemdoutorado
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "150M"

  api-01:
    image: rinha-2024:latest
    container_name: api-01
    ports:
      - 8081:8080
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_DB=rinhadebackend
      - DATABASE_USER=fidelissauro
      - DATABASE_PASSWORD=doutorequemtemdoutorado
      - CACHE_HOST=redis
      - CACHE_PORT=6379
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "125M"
    depends_on:
      - redis
      - postgres

  api-02:
    image: rinha-2024:latest
    container_name: api-02
    ports:
      - 8082:8080
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_DB=rinhadebackend
      - DATABASE_USER=fidelissauro
      - DATABASE_PASSWORD=doutorequemtemdoutorado
      - CACHE_HOST=redis
      - CACHE_PORT=6379
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "125M"
    depends_on:
      - redis
      - postgres
      
volumes:
  redis_data:
  postgres_data:
